name: GitHub Actions Demo yipee
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on:
  push:
    branches:
      - main
jobs:
  determine-changes:
    runs-on: ubuntu-latest
    outputs:
      HAS_APP_CHANGES: ${{ steps.changes.outputs.app }}
      HAS_BFF_CHANGES: ${{ steps.changes.outputs.bff }}
    steps:
      - uses: actions/checkout@v4
      - name: Determine new changes
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            bff:
              - 'bff/**'
            app:
              - 'app/**'
  app_code_analysis:
    needs: [ determine-changes ]
    if: ${{ needs.determine-changes.outputs.HAS_APP_CHANGES == 'true' }}
    name: Analyze APP code
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'javascript' ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          config-file: ./.github/codeql/app-codeql-config.yml
          languages: ${{ matrix.language }}
          queries: 'security-and-quality'

      - name: Perform APP CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:${{matrix.language}}"


  bff_code_analysis:
    needs: [ determine-changes ]
    if: ${{ needs.determine-changes.outputs.HAS_BFF_CHANGES == 'true' }}
    name: Analyze BFF code
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'javascript' ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          config-file: ./.github/codeql/bff-codeql-config.yml
          languages: ${{ matrix.language }}
          queries: 'security-and-quality'

      - name: Perform BFF CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:${{matrix.language}}"


  appBuild:
    needs: [ determine-changes ]
    if: ${{ needs.determine-changes.outputs.HAS_APP_CHANGES == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo â€œğŸ‰ APP build successful for ${{ github.event_name }} event.â€
  bffBuild:
    needs: [ determine-changes ]
    if: ${{ needs.determine-changes.outputs.HAS_BFF_CHANGES == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo â€œğŸ‰ BFF build successful for ${{ github.event_name }} event.â€
  app-deploy-without-bff:
    needs: [determine-changes, appBuild]
    if: (needs.determine-changes.outputs.HAS_BFF_CHANGES == 'false')
    runs-on: ubuntu-latest
    steps:
      - run: echo â€œğŸ‰ App deployment without bff successful for ${{ github.event_name }}.
  app-deploy:
    needs: [ determine-changes, appBuild, bffBuild ]
    if: (needs.appBuild.result == 'success' && needs.bffBuild.result == 'success')
    runs-on: ubuntu-latest
    steps:
      - run: echo â€œğŸ‰ App deployment with bff successful for ${{ github.event_name }}.
  bff-deploy:
    needs: [ determine-changes, appBuild, bffBuild ]
    if: (needs.appBuild.result == 'success' && needs.bffBuild.result == 'success')
    runs-on: ubuntu-latest
    steps:
      - run: echo â€œğŸ‰ BFF deployment with bff successful for ${{ github.event_name }}.
  bff-deploy-without-app:
    needs: [determine-changes, bffBuild]
    if: (needs.determine-changes.outputs.HAS_APP_CHANGES == 'false')
    runs-on: ubuntu-latest
    steps:
      - run: echo â€œğŸ‰ BFF deployment without app successful for ${{ github.event_name }}.â€
